final dummyJsonListOf43Records = [
  {
    "id": 1,
    "name": "Aarav Sharma",
    "phone": "+919876543210",
    "city": "Mumbai",
    "profile_image": "https://randomuser.me/api/portraits/men/1.jpg",
    "rupee": 75,
  },
  {
    "id": 2,
    "name": "Diya Patel",
    "phone": "+918765432109",
    "city": "Delhi",
    "profile_image": "https://randomuser.me/api/portraits/women/2.jpg",
    "rupee": 32,
  },
  {
    "id": 3,
    "name": "Aryan Singh",
    "phone": "+917654321098",
    "city": "Bangalore",
    "profile_image": "https://randomuser.me/api/portraits/men/3.jpg",
    "rupee": 98,
  },
  {
    "id": 4,
    "name": "Ananya Kumar",
    "phone": "+916543210987",
    "city": "Chennai",
    "profile_image": "https://randomuser.me/api/portraits/women/4.jpg",
    "rupee": 15,
  },
  {
    "id": 5,
    "name": "Advik Reddy",
    "phone": "+915432109876",
    "city": "Hyderabad",
    "profile_image": "https://randomuser.me/api/portraits/men/5.jpg",
    "rupee": 60,
  },
  {
    "id": 6,
    "name": "Ishita Verma",
    "phone": "+914321098765",
    "city": "Kolkata",
    "profile_image": "https://randomuser.me/api/portraits/women/6.jpg",
    "rupee": 48,
  },
  {
    "id": 7,
    "name": "Vihaan Gupta",
    "phone": "+913210987654",
    "city": "Pune",
    "profile_image": "https://randomuser.me/api/portraits/men/7.jpg",
    "rupee": 88,
  },
  {
    "id": 8,
    "name": "Saanvi Joshi",
    "phone": "+912109876543",
    "city": "Ahmedabad",
    "profile_image": "https://randomuser.me/api/portraits/women/8.jpg",
    "rupee": 22,
  },
  {
    "id": 9,
    "name": "Kabir Yadav",
    "phone": "+911098765432",
    "city": "Jaipur",
    "profile_image": "https://randomuser.me/api/portraits/men/9.jpg",
    "rupee": 55,
  },
  {
    "id": 10,
    "name": "Aadya Singh",
    "phone": "+919876543211",
    "city": "Lucknow",
    "profile_image": "https://randomuser.me/api/portraits/women/10.jpg",
    "rupee": 91,
  },
  {
    "id": 11,
    "name": "Rohan Mishra",
    "phone": "+918765432110",
    "city": "Surat",
    "profile_image": "https://randomuser.me/api/portraits/men/11.jpg",
    "rupee": 12,
  },
  {
    "id": 12,
    "name": "Siya Tiwari",
    "phone": "+917654321109",
    "city": "Nagpur",
    "profile_image": "https://randomuser.me/api/portraits/women/12.jpg",
    "rupee": 67,
  },
  {
    "id": 13,
    "name": "Vivaan Pandey",
    "phone": "+916543211098",
    "city": "Indore",
    "profile_image": "https://randomuser.me/api/portraits/men/13.jpg",
    "rupee": 39,
  },
  {
    "id": 14,
    "name": "Navya Chauhan",
    "phone": "+915432110987",
    "city": "Bhopal",
    "profile_image": "https://randomuser.me/api/portraits/women/14.jpg",
    "rupee": 79,
  },
  {
    "id": 15,
    "name": "Reyansh Kumar",
    "phone": "+914321109876",
    "city": "Visakhapatnam",
    "profile_image": "https://randomuser.me/api/portraits/men/15.jpg",
    "rupee": 28,
  },
  {
    "id": 16,
    "name": "Anika Mehra",
    "phone": "+913211098765",
    "city": "Pimpri-Chinchwad",
    "profile_image": "https://randomuser.me/api/portraits/women/16.jpg",
    "rupee": 85,
  },
  {
    "id": 17,
    "name": "Shaurya Kapoor",
    "phone": "+912110987654",
    "city": "Patna",
    "profile_image": "https://randomuser.me/api/portraits/men/17.jpg",
    "rupee": 5,
  },
  {
    "id": 18,
    "name": "Myra Khanna",
    "phone": "+911109876543",
    "city": "Vadodara",
    "profile_image": "https://randomuser.me/api/portraits/women/18.jpg",
    "rupee": 44,
  },
  {
    "id": 19,
    "name": "Kiaan Bajaj",
    "phone": "+919876543212",
    "city": "Ludhiana",
    "profile_image": "https://randomuser.me/api/portraits/men/19.jpg",
    "rupee": 71,
  },
  {
    "id": 20,
    "name": "Prisha Verma",
    "phone": "+918765432121",
    "city": "Agra",
    "profile_image": "https://randomuser.me/api/portraits/women/20.jpg",
    "rupee": 19,
  },
  {
    "id": 21,
    "name": "Dhruv Sharma",
    "phone": "+917654321210",
    "city": "Nashik",
    "profile_image": "https://randomuser.me/api/portraits/men/21.jpg",
    "rupee": 63,
  },
  {
    "id": 22,
    "name": "Aarohi Patel",
    "phone": "+916543212109",
    "city": "Faridabad",
    "profile_image": "https://randomuser.me/api/portraits/women/22.jpg",
    "rupee": 36,
  },
  {
    "id": 23,
    "name": "Arnav Singh",
    "phone": "+915432121098",
    "city": "Meerut",
    "profile_image": "https://randomuser.me/api/portraits/men/23.jpg",
    "rupee": 94,
  },
  {
    "id": 24,
    "name": "Avni Kumar",
    "phone": "+914321210987",
    "city": "Rajkot",
    "profile_image": "https://randomuser.me/api/portraits/women/24.jpg",
    "rupee": 8,
  },
  {
    "id": 25,
    "name": "Atharv Reddy",
    "phone": "+913212109876",
    "city": "Kalyan-Dombivli",
    "profile_image": "https://randomuser.me/api/portraits/men/25.jpg",
    "rupee": 52,
  },
  {
    "id": 26,
    "name": " रिया  Garg",
    "phone": "+919876543213",
    "city": "Prayagraj",
    "profile_image": "https://randomuser.me/api/portraits/women/26.jpg",
    "rupee": 80,
  },
  {
    "id": 27,
    "name": "Aarav Verma",
    "phone": "+918765432132",
    "city": "Jabalpur",
    "profile_image": "https://randomuser.me/api/portraits/men/27.jpg",
    "rupee": 27,
  },
  {
    "id": 28,
    "name": "Sanya Sharma",
    "phone": "+917654321321",
    "city": "Coimbatore",
    "profile_image": "https://randomuser.me/api/portraits/women/28.jpg",
    "rupee": 68,
  },
  {
    "id": 29,
    "name": "Ishaan Kapoor",
    "phone": "+916543213210",
    "city": "Vijayawada",
    "profile_image": "https://randomuser.me/api/portraits/men/29.jpg",
    "rupee": 41,
  },
  {
    "id": 30,
    "name": "Meera Choudhary",
    "phone": "+915432132109",
    "city": "Madurai",
    "profile_image": "https://randomuser.me/api/portraits/women/30.jpg",
    "rupee": 96,
  },
  {
    "id": 31,
    "name": "Dev Khanna",
    "phone": "+914321321098",
    "city": "Raipur",
    "profile_image": "https://randomuser.me/api/portraits/men/31.jpg",
    "rupee": 11,
  },
  {
    "id": 32,
    "name": " Kavya  Gupta",
    "phone": "+913213210987",
    "city": "Chandigarh",
    "profile_image": "https://randomuser.me/api/portraits/women/32.jpg",
    "rupee": 73,
  },
  {
    "id": 33,
    "name": "Arjun Malhotra",
    "phone": "+912132109876",
    "city": "Guwahati",
    "profile_image": "https://randomuser.me/api/portraits/men/33.jpg",
    "rupee": 3,
  },
  {
    "id": 34,
    "name": "Siya Singhania",
    "phone": "+911321098765",
    "city": "Kochi",
    "profile_image": "https://randomuser.me/api/portraits/women/34.jpg",
    "rupee": 58,
  },
  {
    "id": 35,
    "name": "Rohan Dsouza",
    "phone": "+919812345678",
    "city": "Panaji",
    "profile_image": "https://randomuser.me/api/portraits/men/35.jpg",
    "rupee": 82,
  },
  {
    "id": 36,
    "name": "Anaya Rao",
    "phone": "+918765432190",
    "city": "Mangalore",
    "profile_image": "https://randomuser.me/api/portraits/women/36.jpg",
    "rupee": 25,
  },
  {
    "id": 37,
    "name": "Aryan Nair",
    "phone": "+919988776655",
    "city": "Thiruvananthapuram",
    "profile_image": "https://randomuser.me/api/portraits/men/37.jpg",
    "rupee": 70,
  },
  {
    "id": 38,
    "name": "Myra Menon",
    "phone": "+917766554433",
    "city": "Kozhikode",
    "profile_image": "https://randomuser.me/api/portraits/women/38.jpg",
    "rupee": 47,
  },
  {
    "id": 39,
    "name": "Pranav Kulkarni",
    "phone": "+919011223344",
    "city": "Belgaum",
    "profile_image": "https://randomuser.me/api/portraits/men/39.jpg",
    "rupee": 6,
  },
  {
    "id": 40,
    "name": "Tanvi Desai",
    "phone": "+918022334455",
    "city": "Hubli-Dharwad",
    "profile_image": "https://randomuser.me/api/portraits/women/40.jpg",
    "rupee": 93,
  },
  {
    "id": 41,
    "name": "Varun Hegde",
    "phone": "+919123456789",
    "city": "Mysore",
    "profile_image": "https://randomuser.me/api/portraits/men/41.jpg",
    "rupee": 18,
  },
  {
    "id": 42,
    "name": "Ishika Joshi",
    "phone": "+917234567890",
    "city": "Gulbarga",
    "profile_image": "https://randomuser.me/api/portraits/women/42.jpg",
    "rupee": 65,
  },
  {
    "id": 43,
    "name": "Samir Sheikh",
    "phone": "+918345678901",
    "city": "Bhavnagar",
    "profile_image": "https://randomuser.me/api/portraits/men/43.jpg",
    "rupee": 29,
  },
];
